//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Islam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public int A_Id { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleAnnotation { get; set; }
        public string ArticleText { get; set; }
        public Nullable<System.DateTime> ArticleDate { get; set; }
        public int M_M_Id { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
