//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Islam
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurahNumbers
    {
        public int SN_Id { get; set; }
        public int SurahNumber { get; set; }
        public short B_B_Id { get; set; }
        public int S_S_Id { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Surahs Surahs { get; set; }
    }
}
