//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Islam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surahs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Surahs()
        {
            this.Ayats = new HashSet<Ayats>();
            this.SurahNumbers = new HashSet<SurahNumbers>();
        }
    
        public int S_Id { get; set; }
        public string SurahName { get; set; }
        public short B_B_Id { get; set; }
        public Nullable<short> Lang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ayats> Ayats { get; set; }
        public virtual Books Books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurahNumbers> SurahNumbers { get; set; }
    }
}
